# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Namespace',
                'abstract': False,
                'verbose_name_plural': 'Namespaces',
            },
        ),
    ]
