# Generated by Django 4.2.20 on 2025-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='best_comparisons',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
