# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 14:03
from __future__ import unicode_literals

import data.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='key',
            field=data.models.URLKeyField(default=-1, help_text='Alphanumeric unique submission id', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
