# Generated by Django 4.2.18 on 2025-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="aplus_key",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
