# Generated by Django 4.2.18 on 2025-07-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_exercise_best_comparisons"),
        ("data", "0002_submission_aplus_key"),
    ]

    operations = []
