# Generated by Django 2.0 on 2018-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_submission_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tokenizer',
            field=models.CharField(choices=[('skip', 'Skip'), ('scala', 'Scala'), ('python', 'Python'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS')], default='skip', help_text='Tokenizer for the submission contents', max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='override_tokenizer',
            field=models.CharField(blank=True, choices=[('skip', 'Skip'), ('scala', 'Scala'), ('python', 'Python'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS')], max_length=8, null=True),
        ),
    ]
