# Generated by Django 2.0 on 2018-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_update_tokenizer_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerqueue',
            name='failed',
            field=models.BooleanField(default=False, help_text='True if the task failed to be processed and should be handled manually.'),
        ),
    ]
