# Generated by Django 2.0 on 2018-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_providerqueue_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='provider_submission_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
