# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20151016_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='review',
            field=models.IntegerField(choices=[(-10, 'False alert'), (0, 'Unspecified match'), (5, 'Suspicious match'), (10, 'Plagiate'), (1, 'Approved plagiate')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Reviewers for match analysis', to=settings.AUTH_USER_MODEL),
        ),
    ]
