# Generated by Django 2.0 on 2018-04-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_submission_provider_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerqueue',
            name='course',
        ),
        migrations.DeleteModel(
            name='ProviderQueue',
        ),
    ]
