# Generated by Django 2.0 on 2018-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180426_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_checksum',
            field=models.TextField(blank=True, default=None, help_text='MD5 checksum of all characters in the submission source', null=True),
        ),
    ]
