# Generated by Django 2.0 on 2018-06-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_similarity_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(help_text='Unweighted similarity score')),
            ],
        ),
        migrations.AlterField(
            model_name='comparison',
            name='similarity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='similarityfunction',
            name='tokenized_input',
            field=models.BooleanField(help_text='Does this function accept tokenized input or untokenized, unmodified source strings'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='comparison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Comparison'),
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.SimilarityFunction'),
        ),
    ]
