# Generated by Django 2.0 on 2018-06-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180613_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='similarity',
            field=models.FloatField(default=0.0, help_text='Similarity score resulting from the comparison of two submissions. This value should be used as an aggregate of the similarity scores produced by different similarity functions.'),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='comparison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data.Comparison'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tokenizer',
            field=models.CharField(choices=[('skip', 'Skip'), ('scala', 'Scala'), ('python', 'Python'), ('js', 'JavaScript (ECMA 2016)'), ('html', 'HTML5'), ('css', 'CSS')], default='skip', help_text='Tokenizer for the submission contents', max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='override_tokenizer',
            field=models.CharField(blank=True, choices=[('skip', 'Skip'), ('scala', 'Scala'), ('python', 'Python'), ('js', 'JavaScript (ECMA 2016)'), ('html', 'HTML5'), ('css', 'CSS')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='similarityfunction',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='similarityfunction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='similarityfunction',
            name='tokenized_input',
            field=models.BooleanField(help_text='True, if this function accepts as input the untokenized, unmodified, source string'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_similarity',
            field=models.FloatField(blank=True, db_index=True, default=None, help_text='Maximum weighted average over all similarity scores computed by different similarity functions', null=True),
        ),
    ]
