# Generated by Django 2.0 on 2018-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20180620_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='similarity_function',
            field=models.CharField(default='jplag_ext', help_text='Name of the similarity function used to compute the similarity of this comparison', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comparison',
            name='similarity',
            field=models.FloatField(default=None, help_text='Similarity score resulting from the comparison of two submissions. This value should be used as an aggregate of the similarity scores produced by different similarity functions.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together={('submission_a', 'submission_b', 'similarity_function')},
        ),
    ]
