# Generated by Django 2.0 on 2018-06-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_simplify_simimilarity_function_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonresult',
            name='comparison',
        ),
        migrations.RemoveField(
            model_name='comparisonresult',
            name='function',
        ),
        migrations.RemoveField(
            model_name='similarityfunction',
            name='course',
        ),
        migrations.DeleteModel(
            name='ComparisonResult',
        ),
        migrations.DeleteModel(
            name='SimilarityFunction',
        ),
    ]
