# Generated by Django 2.0 on 2018-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_move_foreign_key_models_into_comparison_tuple'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error_string', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_similarity',
            field=models.FloatField(blank=True, db_index=True, default=None, help_text='Maximum weighted average over all similarity scores computed by different similarity functions. Null max_similarity indicates a pending Submission, waiting for matching.', null=True),
        ),
    ]
