# Generated by Django 2.0 on 2018-06-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_create_model_for_task_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskerror',
            name='package',
            field=models.CharField(default='-empty-', max_length=100),
        ),
    ]
