# Generated by Django 2.0 on 2018-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_specify_error_source_namespace_in_task_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Can this Submission be matched'),
        ),
        migrations.AddField(
            model_name='submission',
            name='matched',
            field=models.BooleanField(default=False, help_text='Is this Submission waiting to be matched'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_similarity',
            field=models.FloatField(db_index=True, default=0.0, help_text='Maximum weighted average over all similarity scores computed by different similarity functions.'),
        ),
    ]
