# Generated by Django 2.0 on 2018-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_replace_null_punning_with_explicit_state_booleans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Is this Submission invalid in a way it cannot be matched'),
        ),
    ]
