# Generated by Django 2.0 on 2018-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_fix_field_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='matches_json',
            field=models.TextField(blank=True, default=None, help_text='JSON-serialized array of 3-element arrays, containing the index mappings and lengths of matches. E.g. [[i, j, n], ... ] where n is the match length, i starting index of the match in submission_a, and j in submission_b.', null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='similarity',
            field=models.FloatField(default=None, help_text='Similarity score resulting from the comparison of two submissions.', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_similarity',
            field=models.FloatField(db_index=True, default=0.0, help_text='Maximum average similarity.'),
        ),
    ]
