# Generated by Django 2.0 on 2018-07-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_update_help_texts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together={('submission_a', 'submission_b')},
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='similarity_function',
        ),
    ]
