# Generated by Django 2.0 on 2018-07-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_drop_multiple_similarity_func_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='similarity_graph_expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='similarity_graph_json',
            field=models.TextField(default='[]', help_text='Serialized graph showing similarity over all exercises of this course'),
        ),
    ]
