# Generated by Django 2.0 on 2018-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_task_errors_with_namespace_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='matching_start_time',
            field=models.DateTimeField(blank=True, default=None, help_text='None if submission is not currently being matched. If not None, then this submission is currently being matched and waiting for results.', null=True),
        ),
    ]
