# Generated by Django 2.0 on 2019-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_store_timestamp_when_matching_begins'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='matching_start_time',
            field=models.DateTimeField(blank=True, default=None, help_text='If not None, then a timestamp of when all submissions to this exercise started matching. If None, then this exercise is not currently waiting for results from matching.', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='matching_start_time',
            field=models.DateTimeField(blank=True, default=None, help_text='If not None, then this submission is currently being matched and waiting for results. None if submission is not currently being matched.', null=True),
        ),
    ]
