# Generated by Django 2.0 on 2019-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_store_timestamps_as_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='matching_start_time',
            field=models.CharField(blank=True, default=None, help_text='If not None, then this submission is currently being matched and waiting for results. None if submission is not currently being matched.', max_length=50, null=True),
        ),
    ]
