# Generated by Django 2.0 on 2019-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_store_timestamps_as_charfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='similarity_graph_json',
            field=models.TextField(blank=True, default='', help_text='JSON-serialized string of the similarity graph definition returned by data.graph.generate_match_graph'),
        ),
    ]
