# Generated by Django 2.0 on 2019-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_store_similarity_graph_in_course_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Descriptive course name', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='unknown', help_text='Descriptive exercise name', max_length=255),
        ),
    ]
