# Generated by Django 2.2.16 on 2020-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_allow_longer_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='watermark',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='review',
            field=models.IntegerField(choices=[(-10, 'Cleared'), (0, 'Unchecked'), (1, 'Approve copying'), (5, 'Follow'), (10, 'Report')], default=0),
        ),
    ]
