# Generated by Django 2.2 on 2020-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_allow_longer_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='watermark',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
