# Generated by Django 2.2.24 on 2021-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_submission_max_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='No Email', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='No Name', help_text='Full name of the student', max_length=64),
        ),
    ]
