# Generated by Django 2.2 on 2020-08-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_submission_watermark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='watermark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
