# Generated by Django 4.2.11 on 2024-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_auto_20211201_0442"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_generated",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_raw_timestamp",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_status",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_timestamp",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
