# Generated by Django 2.2.15 on 2020-08-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200806_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='review',
            field=models.IntegerField(choices=[(-10, 'Cleared'), (0, 'Unchecked'), (1, 'Approve copying'), (5, 'Follow'), (10, 'Report')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='watermark',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
