# Generated by Django 2.2.15 on 2020-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20200819_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='watermark',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
