# Generated by Django 4.2.18 on 2025-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0031_exercise_dolos_report_generated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tokenizer",
            field=models.CharField(
                choices=[
                    ("skip", "Skip"),
                    ("scala", "Scala"),
                    ("python", "Python"),
                    ("js", "JavaScript (ECMA 2016)"),
                    ("html", "HTML5"),
                    ("css", "CSS"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("matlab", "MATLAB"),
                ],
                default="skip",
                help_text="Tokenizer for the submission contents",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="override_tokenizer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skip", "Skip"),
                    ("scala", "Scala"),
                    ("python", "Python"),
                    ("js", "JavaScript (ECMA 2016)"),
                    ("html", "HTML5"),
                    ("css", "CSS"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("matlab", "MATLAB"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
