# Generated by Django 4.2.11 on 2024-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_rename_dolos_report_exercise_dolos_report_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_generated",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
