# Generated by Django 4.2.11 on 2024-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0034_exercise_dolos_report_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_status",
            field=models.TextField(blank=True, default=""),
        ),
    ]
