# Generated by Django 4.2.11 on 2024-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0036_exercise_template_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
