# Generated by Django 4.2.11 on 2024-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0037_exercise_dolos_report_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_raw_timestamp",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
