# Generated by Django 4.2.11 on 2024-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_exercise_dolos_report_raw_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="dolos_report_id",
            field=models.TextField(blank=True, default=""),
        ),
    ]
