# Generated by Django 3.2.4 on 2021-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180309_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radaruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
