from django.urls import re_path

from review.views import (
    build_graph,
    clusters_view,
    cluster_view,
    comparison,
    configure_course,
    course,
    course_home,
    course_histograms,
    toggle_student_pin,
    download_dataset_zip,
    download_flagged_csv,
    download_student_timestamps_csv,
    download_timestamps_csv,
    dolos_proxy_api_view,
    dolos_proxy_view,
    dolos_hub,
    dolos_hub_refresh_submissions,
    dolos_hub_report,
    check_refresh_submissions_task,
    exercise,
    exercise_settings,
    flagged_pairs,
    generate_course_dolos_view,
    generate_course_dolos_async,
    check_course_dolos_task,
    check_course_dolos_task_current,
    create_cheatersheet_comparison,
    create_cheatersheet_comparison_from_dolos,
    flag_new_radar_pair,
    generate_cross_course_dolos_view,
    generate_dolos_view,
    go_to_dolos_view,
    graph_ui,
    index,
    invalidate_graph_cache,
    marked_submissions,
    pair_view,
    pair_view_summary,
    students_view,
    student_view,
    students_hub,
    student_pair_hub,
    student_hub,
    student_group_hub,
    dolos_mini_comparison,
    toggle_radar_mode,
)


urlpatterns = [
    re_path(
        r'^$',
        index,
        name='index'
    ),
    re_path(
        r'^toggle_radar$',
        toggle_radar_mode,
        name='toggle_radar_mode'
    ),
    re_path(
        r'^cross_course_dolos$',
        generate_cross_course_dolos_view,
        name='cross_course_dolos'
    ),
    re_path(
        r'^(?P<course_key>\w+)/$',
        course,
        name='course'
    ),
    re_path(
        r'^(?P<course_key>\w+)/home/$',
        course_home,
        name='course_home'
    ),
    re_path(
        r'^(?P<course_key>\w+)/home/students/(?P<student_key>\w+)/pin/$',
        toggle_student_pin,
        name='toggle_student_pin'
    ),
    re_path(
        r'^(?P<course_key>\w+)/course_dolos$',
        generate_course_dolos_view,
        name='course_dolos'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/$',
        dolos_hub,
        name='dolos_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/students/$',
        students_hub,
        name='students_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/students/(?P<student_key>\w+)/$',
        student_hub,
        name='student_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/students/pair/(?P<a_key>\w+)-(?P<b_key>\w+)/$',
        student_pair_hub,
        name='student_pair_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/students/pair/'
        r'(?P<a_key>\w+)-(?P<b_key>\w+)/mini/(?P<exercise_key>\w+)/'
        r'(?P<left_submission_id>\d+)-(?P<right_submission_id>\d+)/$',
        dolos_mini_comparison,
        name='dolos_mini_comparison'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/students/group/(?P<member_keys>[\w-]+)/$',
        student_group_hub,
        name='student_group_hub'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/cheatersheet/'
        r'(?P<left_submission_id>\d+)-(?P<right_submission_id>\d+)/$',
        create_cheatersheet_comparison,
        name='create_cheatersheet_comparison'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/flag/'
        r'(?P<left_submission_id>\d+)-(?P<right_submission_id>\d+)/$',
        flag_new_radar_pair,
        name='flag_new_radar_pair'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/cheatersheet/report/'
        r'(?P<report_id>[\w-]+)/(?P<pair_id>\d+)/$',
        create_cheatersheet_comparison_from_dolos,
        name='create_cheatersheet_comparison_from_dolos'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/refresh_submissions/$',
        dolos_hub_refresh_submissions,
        name='dolos_hub_refresh_submissions'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/refresh_submissions/status/$',
        check_refresh_submissions_task,
        name='check_refresh_submissions_task'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/(?P<exercise_key>\w+)/$',
        dolos_hub,
        name='dolos_hub_exercise'
    ),
    re_path(
        r'^(?P<course_key>\w+)/dolos_hub/(?P<exercise_key>\w+)/report/$',
        dolos_hub_report,
        name='dolos_hub_exercise_report'
    ),
    re_path(
        r'^(?P<course_key>\w+)/histogram/$',
        course_histograms,
        name='course_histograms'
    ),
    re_path(
        r'^(?P<course_key>\w+)/configure/$',
        configure_course,
        name='configure_course'
    ),
    re_path(
        r'^(?P<course_key>\w+)/marked/$',
        marked_submissions,
        name='marked_submissions'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/$',
        graph_ui,
        name='graph_ui'
    ),
    re_path(
        r'^(?P<course_key>\w+)/clusters/$',
        clusters_view,
        name='clusters_view'
    ),
    re_path(
        # Cluster key must be integer
        r'^(?P<course_key>\w+)/clusters/(?P<cluster_key>\d+)/$',
        cluster_view,
        name='cluster_view'
    ),
    re_path(
        r'^(?P<course_key>\w+)/students/$',
        students_view,
        name='students_view'
    ),
    re_path(
        r'^(?P<course_key>\w+)/students/(?P<student_key>\w+)/$',
        student_view,
        name='student_view',
    ),
    re_path(
        r'^(?P<course_key>\w+)/generate_course_dolos/$',
        generate_course_dolos_async,
        name='generate_course_dolos_async'
    ),
    re_path(
        r'^(?P<course_key>\w+)/check_dolos_task/(?P<task_id>[\w-]+)/$',
        check_course_dolos_task,
        name='check_course_dolos_task'
    ),
    re_path(
        r'^(?P<course_key>\w+)/check_dolos_task_current/$',
        check_course_dolos_task_current,
        name='check_course_dolos_task_current'
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<a_key>\w+)-(?P<b_key>\w+)/$',
        pair_view,
        name='pair_view',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<a_key>\w+)-(?P<b_key>\w+)/summary/$',
        pair_view_summary,
        name='pair_view_summary',
    ),
    re_path(
        r'^(?P<course_key>\w+)/flagged_pairs/$',
        flagged_pairs,
        name='flagged_pairs'
    ),
    re_path(
        r'^(?P<course_key>\w+)/download/flagged.csv$',
        download_flagged_csv,
        name='download_flagged_csv'
    ),
    re_path(
        r'^(?P<course_key>\w+)/download/timestamps.csv$',
        download_timestamps_csv,
        name='download_timestamps_csv'
    ),
    re_path(
        r'^(?P<course_key>\w+)/download/dataset.zip$',
        download_dataset_zip,
        name='download_dataset_zip'
    ),
    re_path(
        r'^(?P<course_key>\w+)/download/students/(?P<student_key>\w+)/timestamps.csv$',
        download_student_timestamps_csv,
        name='download_student_timestamps_csv'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/build$',
        build_graph,
        name='build_graph'
    ),
    re_path(
        r'^(?P<course_key>\w+)/graph/invalidate$',
        invalidate_graph_cache,
        name='invalidate_graph_cache',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/$',
        exercise,
        name='exercise'
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/settings/$',
        exercise_settings,
        name='exercise_settings',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/compare/(?P<ak>\w+)-(?P<bk>\w+)/(?P<ck>\w+)$',
        comparison,
        name='comparison',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/(?P<best_submissions>\w+)/(?P<flagged>\w+)/gen_dolos$',
        generate_dolos_view,
        name='dolos',
    ),
    re_path(
        r'^(?P<course_key>\w+)/(?P<exercise_key>\w+)/dolos$',
        go_to_dolos_view,
        name='go_to_dolos',
    ),
    re_path(
        r'^dolos-proxy/(?P<path>.*)$',
        dolos_proxy_view.as_view(),
        name='dolos_proxy'
    ),
    re_path(
        r'^dolos-api-proxy/(?P<path>.*)$',
        dolos_proxy_api_view.as_view(),
        name='dolos_api_proxy'
    ),
]
