#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=aplus
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/aplus
ensure_dir /local/aplus
ensure_dir /local/aplus/static
ensure_dir /local/aplus/media

ensure_dir /local/lti-services-in 2777 root root

printf "http://%s:8000" "$(hostname -i)" > /var/run/s6/container_environment/APLUS_BASE_URL
